import {
  Dimension,
  ImperialUnits,
  MetricUnits,
  Units,
} from "../common/common.constants";

/** Factor to multiply value by to get value in canonical unit for that dimension. */
export const UNIT_TO_CANONICAL: Record<Units, number> = {
  [MetricUnits.MM]: 0.1,
  [MetricUnits.CM]: 1,
  [MetricUnits.M]: 100,
  [MetricUnits.KM]: 100_000,
  [ImperialUnits.IN]: 2.54,
  [ImperialUnits.FT]: 30.48,
  [ImperialUnits.YD]: 91.44,
  [ImperialUnits.MI]: 160934.4,
  [MetricUnits.G]: 0.001,
  [MetricUnits.KG]: 1,
  [MetricUnits.TONNE]: 1000,
  [MetricUnits.CELSIUS]: 1,
  [MetricUnits.KELVIN]: 1,
  [ImperialUnits.FAHRENHEIT]: 1,
  [ImperialUnits.OZ]: 0.028349523125,
  [ImperialUnits.LB]: 0.45359237,
  [ImperialUnits.ST]: 6.35029318,
  [MetricUnits.M_S]: 3.6,
  [MetricUnits.KM_H]: 1,
  [ImperialUnits.FT_S]: 1.09728,
  [ImperialUnits.MPH]: 1.609344,
};

export const UNIT_DIMENSION: Record<Units, Dimension> = {
  [MetricUnits.MM]: Dimension.LENGTH,
  [MetricUnits.CM]: Dimension.LENGTH,
  [MetricUnits.M]: Dimension.LENGTH,
  [MetricUnits.KM]: Dimension.LENGTH,
  [ImperialUnits.IN]: Dimension.LENGTH,
  [ImperialUnits.FT]: Dimension.LENGTH,
  [ImperialUnits.YD]: Dimension.LENGTH,
  [ImperialUnits.MI]: Dimension.LENGTH,
  [MetricUnits.G]: Dimension.WEIGHT,
  [MetricUnits.KG]: Dimension.WEIGHT,
  [MetricUnits.TONNE]: Dimension.WEIGHT,
  [MetricUnits.CELSIUS]: Dimension.TEMPERATURE,
  [MetricUnits.KELVIN]: Dimension.TEMPERATURE,
  [ImperialUnits.FAHRENHEIT]: Dimension.TEMPERATURE,
  [ImperialUnits.OZ]: Dimension.WEIGHT,
  [ImperialUnits.LB]: Dimension.WEIGHT,
  [ImperialUnits.ST]: Dimension.WEIGHT,
  [MetricUnits.M_S]: Dimension.SPEED,
  [MetricUnits.KM_H]: Dimension.SPEED,
  [ImperialUnits.FT_S]: Dimension.SPEED,
  [ImperialUnits.MPH]: Dimension.SPEED,
};
